baseURL = "https://blog.xyemy.com/"
languageCode = "zh-CN" # 语言
title = "egg blog" # 标题

theme = "maupassant" #主题名字

summaryLength = 20
uglyurls = true

[author]
name = "xuye" #作者


[params]
localSearch = true #开启搜索
fancybox = true
busuanzi = true #不蒜子计数器
relativeURLs = false
subtitle = "只有魔法才能打败魔法" #副标题
# customJS = ['douban.js'] #需要另外加载的js

[taxonomies]
tag = "tags"
category = "categories"

[params.utteranc]
    enable = true
    repo = "xuye97/xuye97.github.io"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两
